Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Max: 25
  Exclude:
    - "spec/**/*"

Layout/LineLength:
  Max: 100
  IgnoredPatterns: ['\A#']

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/Documentation:
  Enabled: false

AllCops:
  Exclude:
    - "node_modules/**/*"
    - "vendor/**/*"
    - "db/schema.rb"
    - "config/initializers/*"
    - "bin/*"
