Metrics/MethodLength:
  Max: 25

Metrics/BlockLength:
  Max: 25
  Exclude:
    - "spec/**/*"
    - "config/environments/*"
    - "config/routes.rb"

Metrics/ModuleLength:
  Max: 150

Metrics/ClassLength:
  Max: 150

Layout/LineLength:
  Max: 100
  IgnoredPatterns: ['\A#']

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

AllCops:
  Exclude:
    - "node_modules/**/*"
    - "vendor/**/*"
    - "db/schema.rb"
    - "config/initializers/*"
    - "bin/*"
    - "db/migrate/*.active_storage.rb"
