production:
  endpoint: "http://www.google-analytics.com/collect"
  version: 1
  tracking_code: UA-167571882-1

test:
  endpoint: "http://www.google-analytics.com/collect"
  version: 1
  tracking_code: UA-99999999-1

development:
  endpoint: "http://www.google-analytics.com/collect"
  version: 1
  tracking_code: UA-99999999-1
