meta_website: "| experiment.rocks"
meta_title: "Experiment.rocks - your Happiness Lab"
meta_description: "Discover your happiest life - one experiment at a time! Track how you're feeling and try life experiments to find out what makes YOU happy."
